server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
      - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
#        uri: http://localhost:9001   #匹配后提供服务的路由地址
        uri: lb://CLOUD-PAYMENT-SERVICE
        predicates:
          - Path=/payment/get/**   #断言,路径相匹配的进行路由
          - After=2023-02-14T08:56:44.683+08:00[Asia/Shanghai]

      - id: payment_routh2
#        uri: http://localhost:9001
        uri: lb://CLOUD-PAYMENT-SERVICE
        predicates:
          - Path=/payment/lb/**   #断言,路径相匹配的进行路由
          - Cookie=username,zhangsan


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eurekaServer1:7001/eureka


