server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://eurekaServer1:7001/eureka,http://eurekaServer1:7002/eureka
      defaultZone: http://eurekaServer1:7001/eureka




